import html2canvas from "html2canvas";
import jsPDF from "jspdf";

import type { Message } from "@/types/chat.types";

/**
 * Export conversation to PDF
 */
export async function exportConversationToPDF(
  conversationTitle: string,
  messages: Message[]
): Promise<void> {
  // Create an isolated iframe to avoid CSS conflicts
  const iframe = document.createElement("iframe");
  iframe.style.position = "absolute";
  iframe.style.left = "-9999px";
  iframe.style.top = "0";
  iframe.style.width = "800px";
  iframe.style.height = "1px";
  iframe.style.border = "none";
  document.body.appendChild(iframe);

  const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!iframeDoc) {
    document.body.removeChild(iframe);
    throw new Error("Failed to create iframe document");
  }

  const container = iframeDoc.createElement("div");
  container.style.width = "800px";
  container.style.padding = "40px";
  container.style.backgroundColor = "#ffffff";
  container.style.fontFamily = "Arial, sans-serif";
  container.style.color = "#000000";
  iframeDoc.body.appendChild(container);

  try {
    const exportDate = new Date().toLocaleString("bg-BG", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });

    let html = `
      <div style="font-family: Arial, sans-serif; color: #000;">
        <h1 style="font-size: 24px; margin-bottom: 10px; color: #1a1a1a;">EVTA Consult - ДДС AI</h1>
        <h2 style="font-size: 18px; margin-bottom: 10px; color: #333;">${
          conversationTitle || "Експорт на разговор"
        }</h2>
        <p style="font-size: 12px; color: #666; margin-bottom: 20px;">Експортиран на: ${exportDate}</p>
        <hr style="border: none; border-top: 1px solid #ddd; margin-bottom: 20px;" />
    `;

    messages.forEach((message, index) => {
      const roleColor =
        message.role === "user"
          ? "#3b82f6"
          : message.role === "assistant"
          ? "#10b981"
          : "#666";
      const roleLabel =
        message.role === "user"
          ? "User"
          : message.role === "assistant"
          ? "AI Assistant"
          : "System";

      let cleanContent = message.content
        .replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")
        .replace(/\*(.*?)\*/g, "<em>$1</em>")
        .replace(/`(.*?)`/g, "<code>$1</code>")
        .replace(/#{1,6}\s/g, "")
        .replace(/\n/g, "<br/>")
        .trim();

      html += `
        <div style="margin-bottom: 20px;">
          <div style="font-weight: bold; color: ${roleColor}; margin-bottom: 5px; font-size: 13px;">${roleLabel}:</div>
          <div style="font-size: 12px; line-height: 1.6; color: #1a1a1a; white-space: pre-wrap; word-wrap: break-word;">${cleanContent}</div>
          ${
            index < messages.length - 1
              ? '<hr style="border: none; border-top: 1px solid #eee; margin-top: 15px;" />'
              : ""
          }
        </div>
      `;
    });

    html += `
        <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; font-size: 10px; color: #999;">
          Generated by EVTA Consult AI - www.evtaconsult.com
        </div>
      </div>
    `;

    container.innerHTML = html;

    // Wait for fonts and images to load
    await new Promise((resolve) => setTimeout(resolve, 100));

    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      logging: false,
      backgroundColor: "#ffffff",
      foreignObjectRendering: false,
      allowTaint: true,
      removeContainer: false,
    });

    const imgWidth = 210; // A4 width in mm
    const pageHeight = 297; // A4 height in mm
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    pdf.addImage(
      canvas.toDataURL("image/png"),
      "PNG",
      0,
      position,
      imgWidth,
      imgHeight
    );
    heightLeft -= pageHeight;

    // Add additional pages if needed
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(
        canvas.toDataURL("image/png"),
        "PNG",
        0,
        position,
        imgWidth,
        imgHeight
      );
      heightLeft -= pageHeight;
    }

    const filename = `evta_conversation.pdf`;

    pdf.save(filename);
  } finally {
    document.body.removeChild(iframe);
  }
}
