import fs from "fs";
import path from "path";
import * as pdfjsLib from "pdfjs-dist/legacy/build/pdf.mjs";

interface VATArticle {
  article_number: string;
  content: string;
}

/**
 * Extract text from PDF file using pdfjs-dist
 */
async function extractPDFText(pdfPath: string): Promise<string> {
  const dataBuffer = fs.readFileSync(pdfPath);
  const uint8Array = new Uint8Array(dataBuffer);

  const loadingTask = pdfjsLib.getDocument({
    data: uint8Array,
    useSystemFonts: true,
  });

  const pdfDocument = await loadingTask.promise;
  const numPages = pdfDocument.numPages;

  let fullText = "";

  for (let pageNum = 1; pageNum <= numPages; pageNum++) {
    const page = await pdfDocument.getPage(pageNum);
    const textContent = await page.getTextContent();

    // Combine text items
    const pageText = textContent.items.map((item: any) => item.str).join(" ");

    fullText += pageText + "\n";
  }

  return fullText;
}

/**
 * Parse ЗДДС (VAT Act) articles
 * Format: "Чл. X" or "Чл. X."
 */
function parseZDDS(text: string): VATArticle[] {
  const articles: VATArticle[] = [];

  text = text.replace(/\r\n/g, "\n").replace(/\f/g, "\n").replace(/\s+/g, " ");

  // 1. Match "Чл." followed by optional spaces, then number
  const parts = text.split(/(?=Чл\.\s+\d+[а-я]?)/);

  for (const part of parts) {
    // 2. Extract article number from the beginning
    const match = part.match(/^Чл\.\s+(\d+[а-я]?)\s*\.?\s*(.*)/s);

    if (!match) continue;

    const articleNumber = match[1].trim();
    let content = match[2].trim();

    // 2.1. Skip if content is too short (likely parsing error or header)
    if (content.length < 20) continue;

    // 3. Remove any trailing content that belongs to next article
    // Stop at next "Чл." or "§" marker
    const endMatch = content.match(/(.*?)(?=Чл\.\s+\d+|§\s+\d+|$)/s);
    if (endMatch) {
      content = endMatch[1].trim();
    }

    articles.push({
      article_number: articleNumber,
      content: `Чл. ${articleNumber}. ${content}`,
    });
  }

  return articles;
}

/**
 * Parse ППЗДДС (Regulations) articles
 * Format: "§ X" or "§ X."
 */
function parsePPZDDS(text: string): VATArticle[] {
  const articles: VATArticle[] = [];

  text = text.replace(/\r\n/g, "\n").replace(/\f/g, "\n").replace(/\s+/g, " ");

  // 1. Split by paragraph markers
  // Match "§" followed by optional spaces, then number
  const parts = text.split(/(?=§\s+\d+[а-я]?)/);

  for (const part of parts) {
    // 2. Extract paragraph number from the beginning
    const match = part.match(/^§\s+(\d+[а-я]?)\s*\.?\s*(.*)/s);

    if (!match) continue;

    const articleNumber = match[1].trim();
    let content = match[2].trim();

    // 2.1. Skip if content is too short (likely parsing error or header)
    if (content.length < 20) continue;

    // 3. Remove any trailing content that belongs to next article
    // Stop at next "§" or "Чл." marker
    const endMatch = content.match(/(.*?)(?=§\s+\d+|Чл\.\s+\d+|$)/s);
    if (endMatch) {
      content = endMatch[1].trim();
    }

    articles.push({
      article_number: articleNumber,
      content: `§ ${articleNumber}. ${content}`,
    });
  }

  return articles;
}

/**
 * Generate TypeScript output file
 */
function generateOutputFile(
  zddsArticles: VATArticle[],
  ppzddsArticles: VATArticle[]
): string {
  const zddsOutput = JSON.stringify(zddsArticles, null, 2);
  const ppzddsOutput = JSON.stringify(ppzddsArticles, null, 2);

  return `/**
 * AUTO-GENERATED VAT CONTENT
 * 
 * Generated by: scripts/parse-vat-pdfs.ts
 * Date: ${new Date().toISOString()}
 * 
 * INSTRUCTIONS:
 * 1. Review the content below for accuracy
 * 2. Copy ZDDS_CONTENT and PPZDDS_CONTENT arrays
 * 3. Paste them into scripts/seed-vat-content.ts
 * 4. Run: npx tsx scripts/seed-vat-content.ts
 */

export const ZDDS_CONTENT = ${zddsOutput};

export const PPZDDS_CONTENT = ${ppzddsOutput};

// Statistics
console.log("ЗДДС Articles:", ZDDS_CONTENT.length);
console.log("ППЗДДС Articles:", PPZDDS_CONTENT.length);
console.log("Total Articles:", ZDDS_CONTENT.length + PPZDDS_CONTENT.length);
`;
}

/**
 * Main function
 */
async function main() {
  const args = process.argv.slice(2);

  if (args.length !== 2) {
    console.error("❌ Error: Please provide paths to both PDF files");
    console.log("\nUsage:");
    console.log("  npx tsx scripts/parse-vat-pdfs.ts <zdds.pdf> <ppzdds.pdf>");
    console.log("\nExample:");
    console.log(
      "  npx tsx scripts/parse-vat-pdfs.ts ./docs/ZDDS.pdf ./docs/PPZDDS.pdf"
    );
    process.exit(1);
  }

  const [zddsPdfPath, ppzddsPdfPath] = args;

  if (!fs.existsSync(zddsPdfPath)) {
    console.error(`❌ Error: ЗДДС PDF not found: ${zddsPdfPath}`);
    process.exit(1);
  }

  if (!fs.existsSync(ppzddsPdfPath)) {
    console.error(`❌ Error: ППЗДДС PDF not found: ${ppzddsPdfPath}`);
    process.exit(1);
  }

  console.log("🔍 Parsing VAT PDFs...\n");

  // 1. Extract ЗДДС
  console.log(`📄 Extracting ЗДДС from: ${zddsPdfPath}`);
  const zddsText = await extractPDFText(zddsPdfPath);
  const zddsArticles = parseZDDS(zddsText);
  console.log(`✅ Found ${zddsArticles.length} ЗДДС articles\n`);

  // 2. Extract ППЗДДС
  console.log(`📄 Extracting ППЗДДС from: ${ppzddsPdfPath}`);
  const ppzddsText = await extractPDFText(ppzddsPdfPath);
  const ppzddsArticles = parsePPZDDS(ppzddsText);
  console.log(`✅ Found ${ppzddsArticles.length} ППЗДДС articles\n`);

  // 3. Generate output
  const outputContent = generateOutputFile(zddsArticles, ppzddsArticles);
  const outputPath = path.join(__dirname, "vat-content-output.ts");

  fs.writeFileSync(outputPath, outputContent, "utf-8");

  console.log("✅ Successfully generated output file!");
  console.log(`📁 Output: ${outputPath}\n`);
  console.log("📊 Statistics:");
  console.log(`   ЗДДС Articles: ${zddsArticles.length}`);
  console.log(`   ППЗДДС Articles: ${ppzddsArticles.length}`);
  console.log(`   Total: ${zddsArticles.length + ppzddsArticles.length}\n`);
  console.log("📝 Next steps:");
  console.log("   1. Review the generated file for accuracy");
  console.log("   2. Copy the arrays into scripts/seed-vat-content.ts");
  console.log("   3. Run: npx tsx scripts/seed-vat-content.ts");
}

main().catch((error) => {
  console.error("❌ Error:", error);
  process.exit(1);
});
